title: Ezeh Chukwunonso Lawrence
logo: Docs/headshot_circle.png
description: Data analyst, Data Science, Process Engineer, Machine Learning Enthusiast
show_downloads: true
theme: jekyll-theme-minimal
