title: Ezeh Chukwunonso Lawrence
logo: docs/assets/ing/headshot_circle.png
description: Data analyst, Data Science, Process Engineer, Machine Learning Enthusiast
show_downloads: true
themes: jekyll-theme-minimal
